image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
  - echo `pwd` # debug
  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check
    - cat build/reports/jacoco/test/html/index.html | perl -wnE'say /Total.*?([0-9]{1,3})%/g' | awk '{printf "Code Coverage %s%%\n", $1;}'

deploy:
  stage: deploy
  script:
    - echo "TODO deploy"

after_script:
  - echo "End CI"
